version: 2

models:
  - name: stg_jaffle_shop__customers
    columns:
      - name: customer_id
        description: "Primary key for customers"
        tests:
          - unique
          - not_null

  - name: stg_jaffle_shop__orders
    columns:
      - name: order_id
        description: "Primary key for orders"
        tests:
          - unique
          - not_null

      - name: status
        description: "Status of the order"
        tests:
          - accepted_values:
              values:
                - completed
                - cancelled
                - pending

      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_jaffle_shop__customers')
              field: customer_id
