-- Create the databases
use role sysadmin;
CREATE DATABASE RAW_SLN_DB;
CREATE DATABASE DEV_SLN_DB;
CREATE DATABASE PROD_SLN_DB;

-- Create the schema in each database
CREATE SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS;
CREATE SCHEMA DEV_SLN_DB.NYC_PARKING_VIOLATIONS;
CREATE SCHEMA PROD_SLN_DB.NYC_PARKING_VIOLATIONS;

-- Grant usage and select on RAW to both dev and prod roles
GRANT USAGE ON DATABASE RAW_SLN_DB TO ROLE dbt_sf_dev_role;
GRANT USAGE ON SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_dev_role;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_dev_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_dev_role;

GRANT USAGE ON DATABASE RAW_SLN_DB TO ROLE dbt_sf_prod_role;
GRANT USAGE ON SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_prod_role;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_prod_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_prod_role;

-- Grant usage and full privileges on DEV to dev role
GRANT USAGE, CREATE SCHEMA ON DATABASE DEV_SLN_DB TO ROLE dbt_sf_dev_role;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA DEV_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_dev_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DEV_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_dev_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_dev_role;

-- Grant usage and full privileges on PROD to prod role
GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_SLN_DB TO ROLE dbt_sf_prod_role;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA PROD_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_prod_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PROD_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_prod_role;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PROD_SLN_DB.NYC_PARKING_VIOLATIONS TO ROLE dbt_sf_prod_role;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE dbt_sf_dev_role;
GRANT USAGE ON WAREHOUSE TRANSFORMING_WH TO ROLE dbt_sf_prod_role;




----- loading the raw data to raw database 
CREATE OR REPLACE TABLE RAW_SLN_DB.NYC_PARKING_VIOLATIONS.dof_parking_violation_codes
----- use snowflake wizard to load data from local file system

CREATE OR REPLACE TABLE RAW_SLN_DB.NYC_PARKING_VIOLATIONS.parking_violations_issued_fiscal_year_2023_sample
----- use snowflake wizard to load data from local file system
